version: "3.9"

services:
  task_tracker:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db  # Persist the SQLite DB
    environment:
      - TZ=Europe/London
    restart: unless-stopped